#!/bin/bash
#emacs: -*- mode: shell-script; c-basic-offset: 4; tab-width: 4; indent-tabs-mode: t -*- 
#ex: set sts=4 ts=4 sw=4 noet:
#
#
# COPYRIGHT: Yaroslav Halchenko 2015
#
# LICENSE: MIT
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#
#--start-at duration:8 \
#--stop-at duration:20 \

# To create a single long file to later figure out original split points

# arguments as produced by match_images.py
echo "\
--start-at duration:8.24357 --stop-at duration:849.24357
--start-at duration:829.05248 --stop-at duration:1690.05248
--start-at duration:1669.9 --stop-at duration:2530.9
--start-at duration:2510.73725 --stop-at duration:3324.73725
--start-at duration:3304.5269 --stop-at duration:4152.5269
--start-at duration:4132.4 --stop-at duration:4993.4
--start-at duration:4973.20054 --stop-at duration:5834.20054
--start-at duration:5813.80204 --stop-at duration:6664.80204" \
| while read opts; do
    echo HandBrakeCLI -i /dev/sr0 \
                 -o INDIANA_JONES_RAIDERS_LOST_ARK.m4v \
                 -w 960 -l 540 \
                 --rate 29.97 -e x264 -b 3690 \
                 -d  \
                 --nlmeans \
                 -R 44.1 -ab 125440 \
                 $opts
done

# for f in ../*/INDIANA_JONES_RAIDERS_LOST_ARK_part_1.m4v INDIANA_JONES_RAIDERS_LOST_ARK.m4v; do mplayer -vo null -ao null -identify -frames 0 $f >| $(basename $f).info; done
# diff INDIANA_JONES_RAIDERS_LOST_ARK_part_1.m4v.info INDIANA_JONES_RAIDERS_LOST_ARK.m4v.info
