#!/bin/bash
#emacs: -*- mode: shell-script; c-basic-offset: 4; tab-width: 4; indent-tabs-mode: t -*- 
#ex: set sts=4 ts=4 sw=4 noet:
#
#
# COPYRIGHT: Yaroslav Halchenko 2015
#
# LICENSE: MIT
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#
#--start-at duration:8 \
#--stop-at duration:20 \

set -eu

CMD=eval
#CMD=echo # for debugging
# To create a single long file to later figure out original split points

part=0
# arguments (start, end) as produced by match_images.py
echo "\
8.24357   849.24357
829.05248 1690.05248
1669.9    2530.9
2510.7372 3324.73725
3304.5269 4152.5269
4132.4    4993.4
4973.2005 5834.20054
5813.8020 6664.80204" \
| while read start end; do
      part=$(($part+1))
	  [ "${start:0:1}" != "#" ] || continue #  skip commented out
	  # we apparently need a duration, not 'end'
	  duration=$(python -c "print(round($end-$start, 2))")
      $CMD HandBrakeCLI -i /dev/sr0 \
                 -o INDIANA_JONES_RAIDERS_LOST_ARK_part${part}.m4v \
                 -w 960 -l 540 \
                 --rate 29.97 -e x264 -b 3690 \
                 -d  \
                 --nlmeans \
                 -R 44.1 -ab 125440 \
                 --start-at duration:$start --stop-at duration:$duration

#	break # XXX
done

# for f in ../*/INDIANA_JONES_RAIDERS_LOST_ARK_part_1.m4v INDIANA_JONES_RAIDERS_LOST_ARK.m4v; do mplayer -vo null -ao null -identify -frames 0 $f >| $(basename $f).info; done
# diff INDIANA_JONES_RAIDERS_LOST_ARK_part_1.m4v.info INDIANA_JONES_RAIDERS_LOST_ARK.m4v.info
